services:
  discovery_server:
    build: .
    container_name: eurekaserver
    ports:
      - "8761:8761"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend_network:
    external: true