services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
     POSTGRES_DB: spring_security
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
