spring:
  server:
    port: 8080
  application:
    name: spring-security
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      springframework:
        security: TRACE
