services:
  app:
    build: .
    container_name: inventory_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventory
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:latest
    container_name: inventory_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    restart: on-failure
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql

networks:
  backend-network:
    name: microservice_backend_network
    external: false